export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';
export const SUBMIT_FAIL = 'SUBMIT_FAIL';
export const SUBMITTING = 'SUBMITTING';
export const FETCHING_PRODUCT = 'FETCHING_PRODUCT';
export const PRODUCT_FETCHED = 'PRODUCT_FETCHED';
export const PRODUCT_FETCH_FAILED = 'PRODUCT_FETCH_FAILED';
